USE [LabTestPortal]
GO

IF EXISTS(SELECT * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME='Person')
BEGIN
	DROP TABLE [dbo].[Person]
END
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Person](
	[Person_id] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[First_Name] [VARCHAR](50) NOT NULL,
	[Last_Name] [VARCHAR](50) NOT NULL,
	[State_id] [INT] NOT NULL,
	[Gender] [CHAR](1) NOT NULL,
	[DOB] [DATETIME] NOT NULL,
	CONSTRAINT FK_StatePerson FOREIGN KEY(State_id) REFERENCES [dbo].[States]
	)



GO

SET ANSI_PADDING OFF
GO


