INSERT INTO STATES VALUES ('AL');
INSERT INTO STATES VALUES ('CA');
INSERT INTO STATES VALUES ('DE');
INSERT INTO STATES VALUES ('FL');
INSERT INTO STATES VALUES ('GA');
INSERT INTO STATES VALUES ('IN');
INSERT INTO STATES VALUES ('TX');
INSERT INTO STATES VALUES ('UT');
